#!/usr/bin/env node

/**
 * 
 * TODO:
 * 
 *  - support for downloading full filmstrips at different temporal resolutions
 *  - support for taking traces
 *  - support for generating SxS videos when passing multiple traces
 *  - support for different "end" params
 *  - should also ensure that we always download max images; unsure about how to handle videos
 */

async function wait(ms=100) {
  return new Promise((res) => {
    setTimeout(res, ms);
  });
};

// Takes an error-back function and returns an await-compatible 
// async function that rejects on error and fulfills on success.
function wrapEBF(ebf, scope) {
  // The last param to the EBF is assumed to be the callback
  // We take whatever arguments are passed and add our own 
  // promise-based handler instead.
  return async function() {
    let res, rej;
    let ret = new Promise((resInt, rejInt) => {
      res = resInt; rej = rejInt;
    });
    ebf.call((scope || this), ...arguments, function(err, data, info) {
      if(err) { return rej(err); }
      res(data);
    });
    return ret;
  }
}
let ebf = wrapEBF;

(async() => {
  let { Command, Option } = await import("commander");
  let { default: ora } = await import("ora");
  let { default: WPT } = await import("webpagetest");
  let os = await import("node:os");
  let fs = await import("node:fs/promises");
  let { join } = await import("node:path");
  let { cwd } = await import("node:process");
  let { default: sharp } = await import("sharp");
  let { spawn } = await import("node:child_process");

  let _hasFFMpeg = undefined;
  async function hasFFMpeg() {
    if(_hasFFMpeg !== undefined) {
      return _hasFFMpeg;
    }
    let ret = new Promise((res, rej) => {
      let which_h = spawn("/usr/bin/which", [ "ffmpeg" ]);
      which_h.stdout.on("data", (d) => { _hasFFMpeg = (!!d.length); });
      which_h.stderr.on("data", (d) => { _hasFFMpeg = false; });
      which_h.on("error", (e) => { rej(); });
      which_h.on("close", () => { res(_hasFFMpeg); });
    });
    return ret;
  }

  async function transcodeToAV1(source, dest) {
    if(!(await hasFFMpeg())) { return false; }
    let marker = `ffmpeg transcode ${source} to av1`;
    let ret = new Promise((res, rej) => {
      let ffmpeg_h = spawn("/usr/bin/ffmpeg", [
        "-y",
        "-i", source,
        "-c:v", "libsvtav1",
        "-crf", "35",
        "-preset", "5",
        "-svtav1-params", "tune=0",
        "-g", "240",
        "-ac", "0",
        "-c:s", "copy",
        dest
      ]);

      let stdout = "";
      let stderr = "";
      ffmpeg_h.stdout.on("data", (d) => { stdout += d; });
      ffmpeg_h.stderr.on("data", (d) => { stderr += d; });

      ffmpeg_h.on("error", (e) => { rej(stderr); });
      ffmpeg_h.on("close", () => {
        if(stderr.includes("Error ")) {
          console.error(stderr);
          rej(false);
        }
        res(true);
      });
    });
    return ret;
  }

  let fetchResults = async (opts={}, ids=[], spinner) => {
    let key = opts.key;
    let indent = opts.prettyPrint ? 2 : 0;
    let outDir = join(cwd(), opts.output);
    // Check to see if the output directory exists and, if not, create it
    try {
      let outDirStats = await fs.stat(outDir);
      if(!outDirStats.isDirectory()) {
        spinner.fail(` specified output directory ${outDir} exists, but is not a directory; aborting.`);
        return 0;
      }
    } catch(e) {
      spinner.info(`no ouput directory, creating: ${outDir}`);
      await fs.mkdir(outDir, { recursive: true });
    }

    // Create per-test output directories, then fetch results
    for (let testId of ids) {
      let testName = testId;
      let testDir = join(outDir, testId);

      // Handle renaming:
      if(testId.includes(":")) {
        let split = testId.split(":");
        testId = split[0];
        testName = split[1];
        testDir = join(outDir, testId);
        let newTestDir = join(outDir, testName);
        try {
          await fs.stat(testDir);
          spinner.start(` Moving ${testDir} to ${newTestDir}`);
          await fs.rename(testDir, newTestDir);
          spinner.succeed(` Moving ${testDir} to ${newTestDir}`);
        } catch (e) { }
        testDir = newTestDir;
      }

      if(opts.clean) {
        try {
          spinner.start(` Cleaning ${testDir}`);
          await fs.rm(testDir, { recursive: true });
          spinner.succeed(` Cleaned ${testDir}`);
        } catch(e) {}
      }

      await fs.mkdir(testDir, { recursive: true });

      // Default to public instance
      // TODO: allow instance config
      let wpt = new WPT("https://www.webpagetest.org", key); 

      // Look for cached results
      let resultsPath = join(testDir, "results.json");
      let results;
      try {
        if (opts.download) { throw "forcing download"; }
        let res = await fs.readFile(resultsPath, { encoding: "utf-8" });
        results = JSON.parse(res);
        if (!results) { throw "cached results error"; }
        spinner.succeed(` Using cached results for test ${testId}`);
      } catch(e) {
        let options = { breakDown: true };
        spinner.start(` Downloading results for test ${testId}`);
        results = (await (ebf(wpt.getTestResults, wpt)(testId, options)))?.data;
        if(results?.statusCode === 400) {
          spinner.fail(`  No results for ${testId}, server returned 400 status`);
          continue;
        }
        await fs.writeFile(
          resultsPath, 
          JSON.stringify(results, null, indent)
        );
        spinner.succeed(` Results downloaded for test ${testId}`);
      }

      let baseData = {
        "id": null,
        "url": null,
        "summary": null,
        "testUrl": null,
        "location": null,
        "from": null,
        "connectivity": null,
        "bwDown": null,
        "bwUp": null,
        "latency": null,
        "plr": null,
        "shaperLimit": null,
        "mobile": null,
        "completed": null,
        "testRuns": null,
      };

      for(let k in baseData) {
        baseData[k] = results[k];
      }

      baseData.testName = testName;
      baseData.optimizedImages = opts.optimizeImages;
      baseData.optimizedVideos = opts.optimizeImages;
      baseData.crux = results?.runs["1"]?.firstView?.CrUX;

      let writeToPath = async (data, path, desc="", replace=false) => {
        try {
          if (replace) { throw "replacing"; }
          await fs.stat(path);
        } catch(e) {
          await fs.writeFile(path, data);
          if (desc) {
            spinner[ replace ? "start" : "succeed"](
              ` Wrote ${desc} to ${path}`
            );
          }
        }
      };

      let sleep = async (ms=100) => {
        return new Promise((res) => { return setTimeout(res, ms)});
      }

      let optimizeToPath = async (path, quiet=false) => {
        if(
           !opts.optimizeImages ||
           !(path.endsWith(".png") || path.endsWith(".jpg"))
        ) {
          return;
        }
        let avifPath = path.slice(0, -4) + ".avif";
        try {
          await fs.stat(avifPath);
        } catch (e) {
          !quiet && spinner.info(` Transcoding ${path}`);
          // Transcode
          let avif = await sharp(path)
                              .avif({ quality: 40, effort: 4 })
                              .toBuffer();
          await fs.writeFile(avifPath, avif);
        }
      }

      let downloadToPath = async (url, path, desc="", replace=false, quiet=false, retries=0, maxRetries=2, delay=500) => {
        try {
          if (opts.download) { throw "forcing download"; }
          await fs.stat(path);
          // !quiet && spinner.info(` Using cached file: ${path}`);
          await optimizeToPath(path, quiet);
        } catch(e) {
          !quiet && spinner.start(` Downloading ${desc}`);
          let resp = await fetch(url.toString(), {
            headers: { "X-WPT-API-KEY": opts.key }
          });
          if (resp.status == 200) {
            await fs.writeFile(path, resp.body);
            await optimizeToPath(path, quiet);
            !quiet && spinner[ replace ? "start" : "succeed"](
              ` Downloaded ${desc}`
            );
          } else {
            spinner.fail(` Failed to download ${url+""}`);

            retries++;
            if(maxRetries && (maxRetries >= retries)) {
              //  Backoff
              let sleepFor = (2 ** retries) * delay;
              spinner.warn(`  Retrying after ${sleepFor / 1000}s`)
              await sleep(sleepFor);
              return await downloadToPath(url, path, desc, replace, quiet, retries, maxRetries, delay);
            }
          }
        }
      };

      let downloadToPathsInParallel = async (
        meta=[], 
        desc, 
        replace=false, 
        maxParallel=8
      ) => {
        let stride = Math.min(meta.length, maxParallel);
        let end = 0;
        let batch = meta.slice(end, stride);
        while(batch.length) {
          spinner.start(` Downloading ${end}-${end + batch.length} of ${meta.length} ${desc}`);
          await Promise.allSettled(batch.map((i) => {
            return downloadToPath(i.url, i.path, "", replace, true);
          }));
          end += stride;
          batch = meta.slice(end, end+stride);
        }
      }

      let runs = results.runs;
      let runCount = 0;
      for(let r in runs) {
        if(!runs[r]["firstView"]?.videoFrames) {
          continue;
        }
        runCount++;
        if(opts.maxRuns && (runCount > opts.maxRuns)) {
          continue; // Skip
        }
        let run = runs[r];
        spinner.start(` Downloading test run images for test ${testId}, run ${r}`);

        let fetchViewImages = async (view="firstView") => {
          let runStr = `${testId}-r:${r}-c:${ view == "firstView" ? 0 : 1}`;
          let viewData = Object.assign({}, baseData);
          viewData.view = view;
          viewData.run = r;
          // Nested objects
          ["pages", "thumbnails", "images", "breakdown"].forEach((o) => {
            viewData[o] = Object.assign({}, run[view][o]);
          });
          // Trim the breakdown object
          for(let type in viewData.breakdown) {
            delete viewData.breakdown[type].color;
          }

          // Direct values
          // 
          // TODO: should we add these?:
          //
          //  loadEvenStart
          //  loadEventEnd
          //  domContentLoadedEventStart
          //  domContentLoadedEventEnd
          //  domInteractive
          //  render
          //  TTIMeasurementEnd
          //  longTasks and interactivePeriods (large?)
          //
          [ 
            "loadTime",
            "docTime",
            "fullyLoaded",
            "firstPaint", 
            "firstContentfulPaint", 
            "firstMeaningfulPaint",
            "lastVisualChange",
            "visualComplete",
            "visualComplete85",
            "visualComplete90",
            "visualComplete95",
            "visualComplete99",
            "SpeedIndex",
            "TotalBlockingTime",
          ].forEach((v) => {
            viewData[v] = run[view][v];
          });
          viewData.layoutShifts = [];
          viewData.lcps = [];
          if(run[view].chromeUserTiming) {
            run[view].chromeUserTiming.forEach((e) => {
              switch(e.name) {
                case "LargestContentfulPaint":
                  viewData.lcps.push(e.time);
                  break;
                case "LayoutShift":
                  viewData.layoutShifts.push(e.time);
                  break;
                default:
                  viewData[e.name] = e.time;
                  break;
              }
            });
            // Compat with old layout
            viewData.LargestContentfulPaint = viewData.lcps.at(-1);
          }

          // 
          // TODO
          //

          // Grab a subset of the timings
          /*
          // run[view]
          //
            "chromeUserTiming": [
              {
                "name": "navigationStart",
                "time": 25
              },
              {
                "name": "fetchStart",
                "time": 33
              },
              {
                "name": "navigationStart",
                "time": 58
              },
              {
                "name": "domLoading",
                "time": 59
              },
              {
                "name": "responseEnd",
                "time": 59
              },
              {
                "name": "domInteractive",
                "time": 59
              },
              {
                "name": "domContentLoadedEventStart",
                "time": 59
              },
              {
                "name": "domContentLoadedEventEnd",
                "time": 59
              },
              {
                "name": "domComplete",
                "time": 59
              },
              {
                "name": "responseEnd",
                "time": 784
              },
              {
                "name": "unloadEventStart",
                "time": 817
              },
              {
                "name": "unloadEventEnd",
                "time": 817
              },
              {
                "name": "markAsMainFrame",
                "time": 820
              },
              {
                "name": "commitNavigationEnd",
                "time": 824
              },
              {
                "name": "domLoading",
                "time": 829
              },
              {
                "name": "firstMeaningfulPaintCandidate",
                "time": 2319
              },
              {
                "name": "firstPaint",
                "time": 2319
              },
              {
                "name": "firstContentfulPaint",
                "time": 2819
              },
              {
                "name": "firstImagePaint",
                "time": 2819
              },
              {
                "name": "domInteractive",
                "time": 8907
              },
              {
                "name": "domContentLoadedEventStart",
                "time": 8907
              },
              {
                "name": "domContentLoadedEventEnd",
                "time": 8907
              },
              {
                "name": "domComplete",
                "time": 8908
              },
              {
                "name": "loadEventStart",
                "time": 8908
              },
              {
                "name": "loadEventEnd",
                "time": 8908
              },
              {
                "name": "firstMeaningfulPaintCandidate",
                "time": 12918
              },
              {
                "name": "firstMeaningfulPaint",
                "time": 12918
              },
              {
                "name": "firstMeaningfulPaint",
                "time": 12918
              },
              {
                "name": "LayoutShift",
                "time": 12928
              },
              {
                "name": "LayoutShift",
                "time": 13360
              },
              {
                "name": "LayoutShift",
                "time": 13538
              },
              {
                "name": "LayoutShift",
                "time": 16062
              },
              {
                "name": "LayoutShift",
                "time": 21913
              },
              {
                "name": "LayoutShift",
                "time": 22739
              },
              {
                "name": "LargestImagePaint",
                "time": 2819
              },
              {
                "name": "LargestContentfulPaint",
                "time": 2819
              },
              {
                "name": "LargestTextPaint",
                "time": 22824
              },
              {
                "name": "TotalLayoutShift",
                "value": 1.2098869250880349
              },
              {
                "name": "CumulativeLayoutShift",
                "value": 1
              }
            ],
          */

          
          let viewDir = join(testDir, "runs", r, view);
          await fs.mkdir(join(viewDir, "filmstrip"), { recursive: true });

          for(let i in run[view].images) {
            let summary = `${i} image for ${testId}, run ${r}, ${view}`;
            let imgPath = join(viewDir, `${i}.png`);
            viewData[i] = `${i}.png`;
            await downloadToPath(run[view].images[i], imgPath, summary, true);
          }

          // Thumbnail image URL:
          //  https://www.webpagetest.org/thumbnail.php?test=240612_AiDcH3_9XB&fit=150&file=video_1/ms_000000.jpg

          viewData.filmstripFrames = [];
          spinner.start(` Downloading filmstrip images for ${testId}, run ${r}, ${view}`);

          // Parallel fetch
          let meta = [];
          for(let frame of run[view].videoFrames) {
            let imageURL = new URL(frame.image);
            // Note: the image URLs here don't respect the "fit" resizing param
            // imageURL.searchParams.set("fit", opts.timelineImageWidth);
            let fn = imageURL.searchParams.get("file");
            let fp = join(viewDir, "filmstrip", fn);
            meta.push({
              url: imageURL,
              path: fp
            })
            let frameCopy = Object.assign({}, frame);
            frameCopy.image = `filmstrip/${fn}`;
            viewData.filmstripFrames.push(frameCopy);
          }
          await downloadToPathsInParallel(
            meta, 
            "filmstrip images", 
            false, 
            opts.parallelDownloads
          );

          // Parse an image to get size, aspect ratio, and other metadata
          if(meta.length > 1) {
            let img0 = sharp(meta[0].path);
            let md = await img0.metadata();
            // Trim out data we don't use
            delete md.depth; 
            delete md.chromaSubsampling;
            delete md.isPalette;
            delete md.hasProfile;
            viewData.filmstripImageData = Object.assign({}, md);
            viewData.filmstripImageAspectRatio = `${md.width} / ${md.height}`;
          }
          spinner.succeed(` Downloaded ${meta.length} filmstrip images for ${testId}, run ${r}, ${view}`);
 

          // Example URL for gif:
          //    https://www.webpagetest.org/video/video.php?tests=240612_AiDcH3_9XB-r:1-c:0&bg=ffffff&text=222222&end=visual&format=gif
          //
          // Example URL for video:
          //    https://www.webpagetest.org/video/video.php?tests=240612_AiDcH3_9XB-r:1-c:0&bg=ffffff&text=222222&end=visual&format=mp4
          // 
          // Direct URL from player <video> tag:
          //    https://www.webpagetest.org/video/video.php?tests=250622_ZiDc92_46F-r:1-c:1

          spinner.start(` Downloading video of ${testId}, run ${r}, ${view}`);
          let timelineVideoPosterPath = join(viewDir, "poster.png");
          let posterURL = new URL("https://www.webpagetest.org/video/poster.php");
          posterURL.searchParams.set("tests", runStr);
          await downloadToPath(
            posterURL, 
            timelineVideoPosterPath, 
            `poster for video of ${testId}, run ${r}, ${view}`
          );

          let timelineVideoPath = join(viewDir, "timeline.mp4");
          let videoURL = new URL("https://www.webpagetest.org/video/video.php");
          videoURL.searchParams.set("tests", runStr);
          // TODO: support other end points, see:
          //
          //  https://github.com/catchpoint/WebPageTest/blob/master/www/video/filmstrip.inc.php#L125
          //
          //
          // Alternatives:
          //  
          //    - "visual"
          //    - "load" 
          //    - "full" 
          //    - "doc" 
          //    - "all" 
          //    - "aft" 
          //
          // Open questions for alternative end points:
          //
          //    - Should we always download to the very latest?
          //    - Should we record each of these so the component 
          //      can decide at runtime? 
          //

          // TODO(slightlyoff): these seem to be causing fetch failures
          //
          // videoURL.searchParams.set("end", "visual");
          // videoURL.searchParams.set("format", "mp4");

          await downloadToPath(
            videoURL, 
            timelineVideoPath, 
            `video of ${testId}, run ${r}, ${view}`
          );

          let timelineGifPath = join(viewDir, "timeline.gif");
          videoURL.searchParams.set("format", "gif");
          await downloadToPath(
            videoURL, 
            timelineGifPath, 
            `gif of ${testId}, run ${r}, ${view}`
          );

          let gif = sharp(timelineGifPath);
          let md = await gif.metadata();
          let id = Object.assign({}, md);
          delete id.delay;
          delete id.depth;
          delete id.isProgressive;
          delete id.hasProfile;
          delete id.hasAlpha;
          viewData.gifImageData = id;
          viewData.gifImageAspectRatio = `${md.width} / ${md.height}`;

          spinner.succeed(` Downloaded video of ${testId}, run ${r}, ${view}`);

          if(opts.optimizeImages && await hasFFMpeg()) {
            let timelineAV1Path = join(viewDir, "timeline.webm");
            try {
              await fs.stat(timelineAV1Path);
            } catch (e) {
              spinner.start(` Transcoding gif of ${testId}, run ${r}, ${view} to AV1`);
              let start = Date.now();
              await transcodeToAV1(timelineGifPath, timelineAV1Path);
              spinner.succeed(` Transcoded gif of ${testId}, run ${r}, ${view} to AV1 in ${Date.now() - start}ms`);
            }
          }

          // Write out the summary for the component to consume
          let viewDataPath = join(viewDir, "timeline.json");
          await writeToPath(
            JSON.stringify(viewData, null, indent), 
            viewDataPath,
            "",
            opts.rebuildTimelines
          );
        };

        // First View
        await fetchViewImages();
        if(!run.repeatView) { continue; }

        // Repeat View
        await fetchViewImages("repeatView");
      }
    }
  };

  let prog = new Command();

  prog.version("0.3.0")
    // TODO: make key required from *some* source
    .addOption(
      new Option("-k, --key <key>", "WPT API key")
            .env("WPT_KEY")
    )
    .addOption(
      new Option("-o, --output <dir>", "Output directory name")
            .default("./wpt-traces")
            .env("WPT_OUT_DIR")
    )
    .addOption(
      new Option("-c, --clean", 
            "Removes existing trace results for specified trace ids from the download directory before fetching.")
            .env("WPT_CLEAN")
    )
    .addOption(
      new Option("-opt, --optimize-images", 
            "Optimize images (re-encode in AVIF)? Slower. For use with the avif='true' parameter of the <wpt-test> element.")
            .env("WPT_OPTIMIZE")
    )
    .addOption(
      new Option("-rt, --rebuild-timelines",
            "Uses cached results.json and media resources, but rebuilds each run's timline.json file. Useful after version upgrades.")
            .env("WPT_REBUILD_TIMELINES")
    )
    .addOption(
      new Option("-pp, --pretty-print", "Pretty-print JSON?")
            .env("WPT_PRETTY_PRINT")
    )
    .addOption(
      new Option("-d, --download", 
            "Force download instead of using cached results")
            .env("WPT_DOWNLOAD")
    )
    .addOption(
      new Option("-p, --parallel-downloads <concurrent>", 
            "Number of images to download in parallel.")
            .default(10)
            .env("WPT_PARALLEL_DOWNLOADS")
            .argParser(parseInt)
    )
    // TODO: implement
    .addOption(
      new Option("-w, --timeline-image-width <width>", 
            "Width (in pixels) to download timeline images.")
            .default(200)
            .env("WPT_TIMELINE_IMAGE_WIDTH")
            .argParser(parseInt)
    )
    .addOption(
      new Option("-j, --json-config <path>",
            "Path to a JSON configuration file. Command-line arguments override values specified in the file.")
            .env("WPT_JSON_CONFIG")
    )
    .addOption(
      new Option("-m, --max-runs <runs>",
            "Maximum number of runs to download resources for. The default (0) indicates uncapped fetching.")
            .default(0)
            .env("WPT_MAX_RUNS")
    )
    .addOption(
      new Option("-q, --quiet", "Avoid logging.").env("WPT_QUIET")
    )
    // .option("-x, --comparison-video", 
    //           "Download a side-by-side comparison video in addition to per-timeline videos.", 200)
    .argument("[ids...]", "WPT test IDs, space separated")
    .addHelpText("before", 
                 `
Fetches results of an existing public WebPageTest run into named output directories, downloading JSON, images, and waterfalls. Then processes them to generate a "timeline.json" file for displaying WPT timelines using the <wpt-timeline> Web Component.

The default output directory is "./wpt-traces" relative to the current working directory. Individual trace data will be saved in directories with a structure of:

wpt-traces
└── 240612_AiDcR6_9Y0
    ├── results.json
    └── runs
        ├── 1
        │   ├── firstView
        │   │   ├── filmstrip
        │   │   │   ├── ms_000000.jpg
        │   │   │   ├── ms_002100.jpg
        │   │   │   ├── ms_002200.jpg
        │   │   │   ├── ms_002300.jpg
        │   │   │   └── ms_003000.jpg
        │   │   ├── timeline.json
        │   │   └── waterfall.png
        │   └── repeatView
        │   │   ├── filmstrip
        │   │   │   ├── ms_000000.jpg
        │   │   |   └── ...
        │   │   ├── timeline.json
        │   │   └── waterfall.png
        └── 2
            ├── firstView
            │   ├── filmstrip
            │   |   └── ...
            │   ├── timeline.json
            │   └── waterfall.png
            └── repeatView
                └── ...

If the provided trace ID includes a ":" charachter, the top-level directory will use the name after ":" instead.

Example:

    ./src/scripts/wpt-fetch --key <your_key> --output <out_dir> 240612_AiDcR6_9Y0

With recommended settings and renaming:

    ./src/scripts/wpt-fetch --optimize --rebuild-timelines --key <your_key> --output <out_dir> 240612_AiDcR6_9Y0:short-name

Example with JSON configuration:

    ./src/scripts/wpt-fetch -j tests.json
`
    )
    .parse(process.argv);
  
  // Options priority (lowest to highest):
  //
  //  - JSON config
  //  - Environment variables
  //  - CLI
  //
  // The second two are already handled by Commander. All we need to do is build
  // a final option set by:
  //
  //  - Generate a list of explicity set
  //  - Generate a list of values that have been defaulted
  //  - Getting values from the JSON config
  //  - Merge in all values that have been explicitly set
  //  - Merge in only unset values that have been defaulted
  //

  let rawOpts = prog.opts();

  let defaulted = {};
  let explicit = {};
  for(let o in prog._optionValueSources) {
    if(prog._optionValueSources[o] === "default") {
      defaulted[o] = rawOpts[o];
    } else {
      explicit[o] = rawOpts[o];
    }
  }
  let jsonOpts = {};
  if(rawOpts.jsonConfig) {
    let jsonFilePath = join(cwd(), rawOpts.jsonConfig);
    try {
      let res = await fs.readFile(jsonFilePath, { encoding: "utf-8" });
      let jsonData = JSON.parse(res);
      if (!jsonData) { throw "config file parse failed"; }

      if (jsonData?.key === "YOUR_KEY_HERE") {
        delete jsonData.key;
      }
      jsonOpts = jsonData;
    } catch(e) {
      console.error(`failed to read: ${jsonFilePath}`);
      console.dir(e);
    }
  }

  let opts = Object.assign({}, defaulted, jsonOpts, explicit);

  let ids = jsonOpts?.ids || prog.args;

  let spinner = ora({
    text: "Starting...",
    isSilent: opts.quiet,
  }).start();
  await fetchResults(opts, ids, spinner);
  spinner.stop();
})();